<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year</name>
   <tag></tag>
   <elementGuidId>0b7745e5-f1aa-411c-944c-62e0f9826dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>255af182-0fa0-4624-8b54-ae4b50997037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f82a92f3-ecf5-4710-8a26-6a2169874a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c87f2671-4a1b-4f56-ad18-d8d16aece20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>d575f689-fac8-4987-a7a3-21e200291fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;year&quot;)</value>
      <webElementGuid>3c9e99f2-ecc1-4b81-bf54-2c638b2fee48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='year']</value>
      <webElementGuid>e65eba19-9816-41a7-87cd-684d1d89a1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderModal']/div/div/div[2]/form/div[6]/input</value>
      <webElementGuid>a1d5c650-a9db-454a-98fa-8696012d0620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>6b1ff818-d431-4a5e-8607-3910e27fa915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'year']</value>
      <webElementGuid>c627b448-e264-4aff-82b7-a3cd4aa4bbc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
